spring.application.name=<Project Name>

# DATABASE

spring.datasource.url=<Database URL>
spring.datasource.username=<Database Username>
spring.datasource.password=<Database Password>
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# APP

app.base-url=<Base URL>

# JWT

jwt.secret=<JWT Secret Key>
jwt.expiry=<JWT Expiration Time in Milliseconds>

# SENDGRID

api_key=<Store SendGrid API key in environment variables>
mail.from=<Sender Email Address>

# REDIS

spring.data.redis.host=localhost
spring.data.redis.port=6379
