spring.application.name=URL-shortener-project

#DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener
spring.datasource.username=root
spring.datasource.password=#Eega260803
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#APP
app.base-url=http://localhost:8080/api

#JWT
jwt.secret=FiF+IFvL4E/75+NtwYbplin/cC58NnuJ4rIB96tmMA5mpugf5hxwjJsBvAtqoJ2Ek4ICLZcgZLytTv26wGSOSamQ8FOr/uSyKAU2ZAJL71H1DLwCVU0=

jwt.expiry=21600000

#API
api_key=${SENDGRID_API_KEY}
mail.from=vinayakasaieega@gmail.com